### ISSUE TITLE
Google Captcha v2 not showing

### ISSUE THREAD

**Issue by samdgea** [aerni/statamic-livewire-forms#22]
So, I Just configure my form input *for this instance my submission form
I did set the `CAPTCHA_KEY` and `CAPTCHA_SECRET` on my .env and when i try it the captcha not showing. Screenshot attached below

![Captcha not showing](https://cdn.abdilah.id/uploads/screenshot-from-2022-08-09-15-43-29.png)

Steps i've done before create this issue

1. Run `php artisan optimize:clear`
2. Use different Browser, even with Incognito Mode
3. Turn off Ad Blocker

**Comment by aerni** [comment]
I see you already opened the same issue here #12. I just created a fresh Statamic install with the addon. The captcha works for me. I don't think this is an issue with this addon. If you believe otherwise, please create a repo that reproduces the issue. Also, make sure that you use `reCAPTCHA type: v2 Tickbox` when creating your captcha on Google.
