### ISSUE TITLE
Add tag from previous dev-main

### ISSUE THREAD

**Issue by ceesvanegmond** [aerni/statamic-livewire-forms#65]
Hi @aerni ,

Is it possible to tag commit 0fb50625d4b85a437b568496380658c2728ee8b5 as 8.1.1 of 8.2.0?
Having a project that isn't compatible with your latest v9 release yet; but does use captcha field in LiveWire 3.
Is this possible? Thanks!

**Comment by aerni** [comment]
I don't understand what you're asking. Version 9 is a complete rewrite for Livewire 3. Any version before that is not completely compatible with Livewire 3. How are you using Livewire 3 without v9 of this addon? Curious, as to what is holding you back from upgrading?

**Comment by ceesvanegmond** [comment]
Good question! Version ^9.0 forces you to be on Statamic v5. I haven't upgraded to v5 yet. It supposed to be a minor update but haven't done it also because the website is quite big.

**Comment by aerni** [comment]
Yeah, so the addon requires Statamic 5 because it relies on features that are not available in Statamic 4. And making v9 compatible with both Statamic 4 and 5 is tedious and not worth the trouble.

If your only issue is the captcha field, you can simply apply the changes in that commit to your published captcha view.
